### ISSUE TITLE
Outgoing connections are being initiated to banned peers

### ISSUE THREAD

**Issue by stasatdaglabs** [kaspanet/kaspad#1497] opened 2021-02-07 11:13 UTC
Every so often, the following can be observed:
```
2021-02-07 13:11:15.148 [INF] TXMP: P2P Dialing to 54.229.69.222:16211
2021-02-07 13:11:15.148 [INF] PROT: Peer <<nil>: 3.250.56.173:16211> is banned. Disconnecting...
```

This likely happens because AddressManager.RandomAddresses does not properly filter out banned addresses.

**Comment by svarogg** [comment] 2021-05-18 11:50
Closed as duplicate of #1122

**Closed by svarogg** 2021-05-18 11:50 UTC
Labels: bug, good first issue, p2p
