### ISSUE TITLE
Kaspad crashes with "error in goroutine 'flow-HandleRelayInvs 297': not found\n key ... not found" message

### ISSUE THREAD

**Issue by Aleoami** [kaspanet/kaspad#1887] opened 2021-12-15 10:51 UTC
While trying to sync from scratch kaspad crashed and reported the following:
2021-12-15 13:18:30.150 [CRT] PROT: Exiting: Fatal error in goroutine 'flow-HandleRelayInvs 297': not found
key 012f0f2f626c6f636b2d72656c6174696f6e732f98ce11799de94ab09e13767c221a6e02a2cbed9b64896fe5c659367ef927dda0 not found. 
Then this error kept appearing every next time kaspad is run. Here is the full DB+logs, archived after the 1st crash: https://transfer.sh/b5vSXj/kaspa-mainnet.rar

UPD: i now managed to successfully sync from scratch once I added custom peers 212.41.9.28, 168.119.79.146 and 65.108.46.86 - all the same from what I successfully synced the previous time. So this issue's source may be some node that's in a kind of 'unaligned' state

**Comment by aspect** [comment] 2021-12-15 15:57
This is a duplicate of https://github.com/kaspanet/kaspad/issues/1886

**Comment by cbytensky** [comment] 2021-12-20 00:06
I can’t download https://transfer.sh/b5vSXj/kaspa-mainnet.rar
Can you upload elsewhere?

**Comment by stasatdaglabs** [comment] 2022-02-06 08:22
Fixed in https://github.com/kaspanet/kaspad/pull/1913

**Closed by stasatdaglabs** 2022-02-06 08:22 UTC
