### ISSUE TITLE
Address manager may run out of viable addresses

### ISSUE THREAD

**Issue by stasatdaglabs** [kaspanet/kaspad#1672] opened 2021-04-11 12:05 UTC
Under certain circumstances, all the addresses within the address manager may no longer be accessible.
Kaspad should recognize this case and attempt to fetch new addresses from the DNS seeder.

**Comment by svarogg** [comment] 2021-05-18 11:29
Closing as duplicate of #1588

**Closed by svarogg** 2021-05-18 11:29 UTC
Labels: bug, error-handling, feature-request, good first issue
